print('M M               M M           GGGGGGGGGGGGGG      ')
print('M  M             M  M           G                   ')
print('M    M          M   M           G                   ')
print('M      M        M   M           G                   ')
print('M       M       M   M           G                   ')
print('M        M     M    M           G    GGGGGGGG    ')
print('M         M    M    M           G             G      ')
print('M          M  M     M           G             G      ')
print('M           M       M           GGGGGGGGGGGGGGG     ')